<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Authentication\Module'                          => __DIR__ . '/Module.php',
  'Authentication\Controller\User\IndexController' => __DIR__ . '/src/Authentication/Controller/User/IndexController.php',
);
