<div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
        <h1 class="text-center login-title">Log in to continue</h1>

        <div class="account-wall">
            <form class="form-signin" method="post">
                <div class="form-group">
                    <input name="username" type="text" class="form-control" placeholder="Email" required autofocus>
                </div>
                <div class="form-group">
                    <input name="password" type="password" class="form-control" placeholder="Password" required>
                </div>

                <?php if (isset($errorMessage)):?>
                    <div class="errorMessage"> <?= $errorMessage  ?></div>
                <?php endif; ?>

                <label class="pull-left">
                    <input type="checkbox" value="remember-me"> Remember me
                </label>

                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                <a href="/" class="pull-right"><i class="fa fa-reply"></i> Go to main </a>
                <a href="#" class="text-center new-account">Forgot pass?</a>
            </form>
        </div>
    </div>
</div>