<form action="<?=$this->url('auth-login');?>" id="signin-form_id" method="POST">
    <div class="signin-text">
        <span>Sign In to your account</span>
    </div>
    <!-- / .signin-text -->

    <div class="form-group w-icon">
        <input type="text" name="username" id="username_id" class="form-control input-lg"
               placeholder="Username or email">
        <span class="fa fa-user signin-form-icon"></span>
    </div>
    <!-- / Username -->

    <div class="form-group w-icon">
        <input type="password" name="password" id="password_id" class="form-control input-lg"
               placeholder="Password">
        <span class="fa fa-lock signin-form-icon"></span>
    </div>

    <?php if (isset($errorMessage)):?>
        <div class="errorMessage"> <?= $errorMessage  ?></div>
    <?php endif; ?>
    <!-- / Password -->

    <div class="form-actions">
        <input type="submit" value="SIGN IN" class="signin-btn bg-primary">
        <a href="#" class="forgot-password" id="forgot-password-link">Forgot your password?</a>
    </div>
    <!-- / .form-actions -->
</form>
<!-- / Form -->

<!-- Password reset form -->
<div class="password-reset-form" id="password-reset-form">
    <div class="header">
        <div class="signin-text">
            <span>Password reset</span>

            <div class="close">&times;</div>
        </div>
        <!-- / .signin-text -->
    </div>
    <!-- / .header -->

    <!-- Form -->
    <form action="index.html" id="password-reset-form_id">
        <div class="form-group w-icon">
            <input type="text" name="password_reset_email" id="p_email_id" class="form-control input-lg"
                   placeholder="Enter your email">
            <span class="fa fa-envelope signin-form-icon"></span>
        </div>
        <!-- / Email -->

        <div class="form-actions">
            <input type="submit" value="SEND PASSWORD RESET LINK" class="signin-btn bg-primary">
        </div>
        <!-- / .form-actions -->
    </form>
    <!-- / Form -->
</div>