<?= $this->doctype(); ?>

<html class="gt-ie8 gt-ie9 not-ie">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Sign In - T4 inside</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <!-- Open Sans font from Google CDN -->
    <link
        href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&amp;subset=latin"
        rel="stylesheet" type="text/css">

    <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favico.png')); ?>

    <!-- LanderApp's stylesheets -->
    <link href="/assets/stylesheets/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/stylesheets/landerapp.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/stylesheets/pages.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/stylesheets/rtl.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/stylesheets/themes.min.css" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
    <script src="/assets/javascripts/ie.min.js"></script>
    <![endif]-->


    <!-- $DEMO =========================================================================================

        Remove this section on production
    -->
    <style>
        #signin-demo {
            position: fixed;
            right: 0;
            bottom: 0;
            z-index: 10000;
            background: rgba(0, 0, 0, .6);
            padding: 6px;
            border-radius: 3px;
        }

        #signin-demo img {
            cursor: pointer;
            height: 40px;
        }

        #signin-demo img:hover {
            opacity: .5;
        }

        #signin-demo div {
            color: #fff;
            font-size: 10px;
            font-weight: 600;
            padding-bottom: 6px;
        }
    </style>
    <!-- / $DEMO -->

</head>


<!-- 1. $BODY ======================================================================================

	Body

	Classes:
	* 'theme-{THEME NAME}'
	* 'right-to-left'     - Sets text direction to right-to-left
-->
<body class="theme-default page-signin">

<script>
    var init = [];
</script>
<!-- Demo script -->
<script src="/assets/demo/demo.js"></script>
<!-- / Demo script -->

<!-- Page background -->
<div id="page-signin-bg">
    <!-- Background overlay -->
    <div class="overlay"></div>
    <!-- Replace this with your bg image -->
    <img src="/assets/demo/signin-bg/<?=rand(1, 38);?>.jpg" alt="">
</div>
<!-- / Page background -->

<!-- Container -->
<div class="signin-container">

    <div class="signin-info">
        <a href="/" class="logo">
            In<span style="font-weight:100;">T4web</span>
        </a> <!-- / .logo -->
        <div class="slogan">
            Simple. Flexible. Powerful.
        </div>
        <ul>
            <li><i class="fa fa-sitemap signin-icon"></i> Flexible modular structure</li>
            <li><i class="fa fa-file-text-o signin-icon"></i> Well Commented Source</li>
            <li><i class="fa fa-outdent signin-icon"></i> Full stack support</li>
            <li><i class="fa fa-heart signin-icon"></i> Crafted with love</li>
        </ul>
    </div>

    <div class="signin-form">
        <?= $this->content; ?>
    </div>
</div>
<!-- / Container -->

<!-- Get jQuery from Google CDN -->
<!--[if !IE]> -->
<script
    type="text/javascript"> window.jQuery || document.write('<script src="/assets/javascripts/jquery.min.js">' + "<" + "/script>"); </script>
<!-- <![endif]-->
<!--[if lte IE 9]>
<script
    type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">' + "<" + "/script>"); </script>
<![endif]-->


<!-- LanderApp's javascripts -->
<script src="/assets/javascripts/bootstrap.min.js"></script>
<script src="/assets/javascripts/landerapp.min.js"></script>

<script type="text/javascript">
    // Resize BG
    init.push(function () {
        var $ph = $('#page-signin-bg'),
            $img = $ph.find('> img');

        $(window).on('resize', function () {
            $img.attr('style', '');
            if ($img.height() < $ph.height()) {
                $img.css({
                    height: '100%',
                    width: 'auto'
                });
            }
        });
    });

    // Show/Hide password reset form on click
    init.push(function () {
        $('#forgot-password-link').click(function () {
            $('#password-reset-form').fadeIn(400);
            return false;
        });
        $('#password-reset-form .close').click(function () {
            $('#password-reset-form').fadeOut(400);
            return false;
        });
    });

    // Setup Sign In form validation
    init.push(function () {
        $("#signin-form_id").validate({
            focusInvalid: true
        });

        // Validate username
        $("#username_id").rules("add", {
            required: true,
            minlength: 3
        });

        // Validate password
        $("#password_id").rules("add", {
            required: true,
            minlength: 6
        });
    });

    // Setup Password Reset form validation
    init.push(function () {
        $("#password-reset-form_id").validate({
            focusInvalid: true, errorPlacement: function () {
            }
        });

        // Validate email
        $("#p_email_id").rules("add", {
            required: true,
            email: true
        });
    });

    window.LanderApp.start(init);
</script>

</body>
</html>
